name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1


    - name: Login ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Set Image Tag
      run: |
        echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV


    # BACKEND

    - name: Build backend
      run: |
        docker build \
        -t tienda-backend:${{ env.IMAGE_TAG }} \
        ./back-Ventas_SpringBoot/Springboot-API-REST


    - name: Push backend
      run: |
        docker tag tienda-backend:${{ env.IMAGE_TAG }} \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:${{ env.IMAGE_TAG }}

        docker push \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:${{ env.IMAGE_TAG }}



    # FRONTEND

    - name: Build frontend
      run: |
        docker build \
        -t tienda-frontend:${{ env.IMAGE_TAG }} \
        ./front_despacho


    - name: Push frontend
      run: |
        docker tag tienda-frontend:${{ env.IMAGE_TAG }} \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:${{ env.IMAGE_TAG }}

        docker push \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:${{ env.IMAGE_TAG }}



    # DEPLOY EKS

    - name: Deploy to EKS
      run: |
        aws eks update-kubeconfig \
        --name devopseks \
        --region us-east-1


        kubectl set image deployment/tienda-backend \
        backend=018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:${{ env.IMAGE_TAG }}


        kubectl set image deployment/tienda-frontend \
        frontend=018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:${{ env.IMAGE_TAG }}


        kubectl rollout status deployment/tienda-backend

        kubectl rollout status deployment/tienda-frontend