name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Login ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build backend ventas
      run: |
        docker build \
        -t tienda-backend \
        ./back-Ventas_SpringBoot/Springboot-API-REST


    - name: Push backend ventas
      run: |
        docker tag tienda-backend:latest \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest

        docker push \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-backend:latest


    - name: Build frontend
      run: |
        docker build \
        -t tienda-frontend \
        ./front_despacho


    - name: Push frontend
      run: |
        docker tag tienda-frontend:latest \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest

        docker push \
        018147952742.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest